//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be lest than 80 characters.
        /// </summary>
        public static string AddressLong {
            get {
                return ResourceManager.GetString("AddressLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be lest than 80 characters.
        /// </summary>
        public static string ChurchAddressLong {
            get {
                return ResourceManager.GetString("ChurchAddressLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be lest than 50 characters.
        /// </summary>
        public static string ChurchNameLong {
            get {
                return ResourceManager.GetString("ChurchNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be lest than {1} characters.
        /// </summary>
        public static string ChurchPastor {
            get {
                return ResourceManager.GetString("ChurchPastor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be lest than 15 characters.
        /// </summary>
        public static string ChurchPhoneLong {
            get {
                return ResourceManager.GetString("ChurchPhoneLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be lest than 50 characters.
        /// </summary>
        public static string CityLong {
            get {
                return ResourceManager.GetString("CityLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be lest than 50 characters.
        /// </summary>
        public static string FirstNameLong {
            get {
                return ResourceManager.GetString("FirstNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is required.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be lest than 50 characters.
        /// </summary>
        public static string LastNameLong {
            get {
                return ResourceManager.GetString("LastNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is required.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string PasswordCompare {
            get {
                return ResourceManager.GetString("PasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be lest than 100 characters.
        /// </summary>
        public static string PasswordLong {
            get {
                return ResourceManager.GetString("PasswordLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone is not valid.
        /// </summary>
        public static string PhoneInvalid {
            get {
                return ResourceManager.GetString("PhoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be lest than 15 characters.
        /// </summary>
        public static string PhoneLong {
            get {
                return ResourceManager.GetString("PhoneLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be lest than 50 characters.
        /// </summary>
        public static string StateLong {
            get {
                return ResourceManager.GetString("StateLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be lest than 50 characters.
        /// </summary>
        public static string UserNameLong {
            get {
                return ResourceManager.GetString("UserNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Name is required.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be lest than 15 characters.
        /// </summary>
        public static string ZipLong {
            get {
                return ResourceManager.GetString("ZipLong", resourceCulture);
            }
        }
    }
}
